# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
  functions = "functions"

[functions]
  included_files = [
    "files/*.json",
    "files/*.md",
    "files/*.txt"
  ]
